services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  
  kafkaserver:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
      - zookeeper
            
  redisserver:
    image: redis:alpine
    ports:
      - 6380:6380

networks:
  default:
    name: goows-kafkas