services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
  
  kafkaserver:
    image: wurstmeister/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
      - 9093:9093
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT  # 커스텀 프로토콜을 위한 변수
      - KAFKA_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./jobs:/opt/kafka/jobs
    depends_on:
      - zookeeper
            
  redisserver:
    image: redis:alpine
    ports:
      - 6380:6380

networks:
  default:
    name: goows-kafkas